version: "3.9"
services:
  demo:
    build: .
    depends_on: 
      - db
    links:
      - db
    volumes:
      - ./app:/home/
  db:
    image: postgres:9.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS="--auth-host=md5"
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
    volumes: 
      - ./db:/docker-entrypoint-initdb.d/
  db-test:
    image: postgres:9.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS="--auth-host=md5"
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5431:5432'
    volumes: 
      - ./db:/docker-entrypoint-initdb.d/
      
volumes:
  db:
    driver: local